# Generated by Django 6.0.6 on 2026-09-10 03:25

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MedicalReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('selected_language', models.CharField(choices=[('english', 'English'), ('hindi', 'Hindi'), ('marathi', 'Marathi'), ('bengali', 'Bengali'), ('tamil', 'Tamil'), ('telugu', 'Telugu')], default='english', max_length=20)),
                ('extracted_text', models.TextField()),
                ('ai_explanation', models.TextField(blank=True)),
                ('risk_category', models.CharField(choices=[('green', 'Green - Safe'), ('yellow', 'Yellow - Consult Doctor'), ('red', 'Red - Urgent')], default='green', max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
