# Generated by Django 6.0.6 on 2026-06-21 04:15

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MedicalReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('report_image', models.ImageField(blank=True, null=True, upload_to='reports/')),
                ('extracted_text', models.TextField(blank=True, null=True)),
                ('ai_explanation', models.TextField(blank=True, null=True)),
                ('risk_category', models.CharField(blank=True, choices=[('green', 'Routine Monitoring'), ('yellow', 'Consult Doctor Soon'), ('red', 'Seek Medical Attention')], max_length=10, null=True)),
                ('selected_language', models.CharField(choices=[('english', 'English'), ('hindi', 'Hindi'), ('marathi', 'Marathi'), ('bengali', 'Bengali'), ('tamil', 'Tamil'), ('telugu', 'Telugu')], default='english', max_length=20)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Medical Report',
                'verbose_name_plural': 'Medical Reports',
                'ordering': ['-uploaded_at'],
            },
        ),
    ]
